source 'https://rubygems.org'

gem 'spree_core (~> 2.2.0.beta) ruby'
# Provides basic authentication functionality for testing parts of your engine
gem 'spree_auth_devise', github: 'spree/spree_auth_devise'

gemspec
